### ISSUE TITLE
Confirm we have a 5v line on the cubesat.

### ISSUE THREAD

**Issue by TheDopplerEffects** [USST-RADSAT-SK/software-and-command#189]
Confirm we have a 5v line on the cubesat, if not remove functionality from Reps.c

**Comment by ATGr8** [comment]
USM-1335 Rev D. Page 30, Section 9.5 Confirms we have a 5V line on the CubeSat

**Comment by TheDopplerEffects** [comment]
@ATGr8 that would just indicate the the board has access to a 5v line on the CSKB but not indicate weather there is 5v on board the OBC. My guess is that is what Addi was concerned about. I doubt Addi didn't know the CubeSat had a 5v line.

**Comment by TheDopplerEffects** [comment]
Actually there is no way Addi didn't know there was a 5v line by the time he left so this issue may be old and never dealt with?
