### ISSUE TITLE
UART Wrapper

### ISSUE THREAD

**Issue by tyrelkostyk** [USST-RADSAT-SK/software-and-command#25]
Implement a simple wrapper around the UART driver provided in the HAL

**Comment by tslotboom** [comment]
Deadline - June 1

**Comment by jacobwaskowic** [comment]
Contains three functions for now:
UART_blockingTransmit():
Inputs:
- Takes in a pointer to data to be sent over UART
- Takes in the size in bytes to be sent
Outputs:
- An integer error code, 0 indicates success. Non-zero indicates a failure, which is specified in UART.h

UART_blockingRecieve():
Inputs:
- Takes in a pointer to a buffer to receive data into from UART
- Takes in the size in bytes to be received
Outputs:
- An integer error code, 0 indicates success. Non-zero indicates a failure, which is specified in UART.h

UART_init():
Initializes UART and enables receiving. Should be ran at the beginning of our main application once.

**Comment by jacobwaskowic** [comment]
Note that these functions are blocking. At some point later on, an additional task to manage these functions would be a good idea.
