### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by tyrelkostyk** [USST-RADSAT-SK/software-and-command#29]

**Comment by tslotboom** [comment]
Deadline - June 1

**Comment by ChrisAmaya** [comment]
The idea of the message module (while referencing the Software Architecture Block Diagram) is to be able to wrap all downlinking messages and unwrap all uplink messages and return the useful data that each message contains 

This module should be able to do the following 

For receiving a message

- [ ] Decrypt messages from uplinks
- [ ] Be able to call the encryption sky
- [ ] Unwrap the protobuf layer

For preparing a message 

- [ ]  Wrap the data with a protobuf layer
- [ ]  define header
