### ISSUE TITLE
Determine why release and debug are sharing symbols

### ISSUE THREAD

**Issue by ChrisAmaya** [USST-RADSAT-SK/software-and-command#42]
Somewhere in our property settings the debug and release configurations are sharing symbols

**Comment by ChrisAmaya** [comment]
One solution: configure specific build scripts for debug and release (last resort)

**Comment by tyrelkostyk** [comment]
Inside the `Project > Properties > C/C++ General > Indexer` page, there was a setting at the bottom that had to be changed to "Use Active Build Configuration" instead of "Use Fixed Build Config". I changed this setting to the proper setting (active) in PR #161 in response to Issue #87
